disabled_rules:
  - force_cast
  - trailing_whitespace

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - SAPISwiftSDKFrameworkTests
  - MapApp
  - MapAppTests